In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
ones = np.ones((3,3))
zeros = np.zeros((2,2))
arr_with_arange = np.arange(15)

In [4]:
ones, zeros, arr_with_arange

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]))

In [5]:
ones.dtype, arr_with_arange.dtype
# Типы данных переданых в векторах или матрицах

(dtype('float64'), dtype('int64'))

In [6]:
arr_with_arange.shape, zeros.shape
# Размерности вектора и матрицы

((15,), (2, 2))

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr[2][1], arr[(2, 1)], arr[2,1] # Разные варианты получения элемента

(np.int64(8), np.int64(8), np.int64(8))

In [9]:
arr[0:2, 0:2] # Получение подмассива с помощью среща

array([[1, 2],
       [4, 5]])

In [10]:
arr + ones # Поэлементное сложение 

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [11]:
arr * ones # Поэлементное перемножение 

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [12]:
arr_with_arange = np.arange(11, 20).reshape(3, 3) # Создание массива с элементами от 11 до 19 включительно с размерностями (3, 3) 
new_arr = arr_with_arange * arr  # Поэлементное перемножение 
new_arr

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [13]:
new_arr.mean(), new_arr.max(), new_arr.min(), new_arr.std() # Статистические функции

(np.float64(81.66666666666667),
 np.int64(171),
 np.int64(11),
 np.float64(51.97007686052512))